### ISSUE TITLE
[成品 Crack 反馈] HeartfulMemories 替换文件后，主程序无法启动

### ISSUE THREAD

**Issue by janjin123** [YeLikesss/CNGALTools#1]
操作系统：Windows 10 22H2 64-bit，未连接互联网

HeartfulMemories 标示版本：V3.0

复现方式：
　　1.解压 HeartfulMemoriesLauncher_v3.0_Release.zip 文件（该文件 SHA-1 为 F32B951F580A223FF0B394BDE3412EB9A8ABFC69）
　　2.下载 8.HeartfulMemories.rar 后解压，得到 Assembly-CSharp.dll 文件（该文件 SHA-1 为 7A0C8C96119CB185F53DA2C4923324F889BB17D4）
　　3.复制 Assembly-CSharp.dll 进 (GameLuncher所在目录)\game\HeartfulMemories_Data\Managed 目录，替换原本存在的同名文件
　　4.双击 (GameLuncher所在目录)\game 目录下的 HeartfulMemories.exe 程序文件 （该文件 SHA-1 为 DAB4D253DAED7B01E1A62783D5E8218BEFB0E226）
　　5.此时，该程序先启动，随即窗口内全白、迅速闪过一疑似 BugReport 的对话框，之后提示“程序未响应”，最终自动关闭

预期行为：HeartfulMemories V3.0 正常启动运行

其他说明：本人已购买该程序 PC 版、移动版正版授权；意识到该游戏无法离网运行后，寻求解决方式过程中，发现了您的研究。

**Comment by janjin123** [comment]
SunnyrainLovestory 有类似问题，未重复开 issue 。

**Comment by YeLikesss** [comment]
哇~ 我没想到这个游戏还能更新，检查后是版本对不上的原因。不过这个系列游戏本人不太喜欢，我已移除成品Crack了，在Note文件夹里面发布了更详细的教程。需要用到的工具 [https://github.com/dnSpyEx/dnSpy](url) 的64位版

**Comment by janjin123** [comment]
> 哇~ 我没想到这个游戏还能更新，检查后是版本对不上的原因。不过这个系列游戏本人不太喜欢，我已移除成品Crack了，在Note文件夹里面发布了更详细的教程。IF篇需要改图片里面的2个函数，S篇只有其中一个函数。需要用到的工具 [https://github.com/dnSpyEx/dnSpy](url) 的64位版

感谢您的回复和解答！

按照新的教程修正 DLL 后，两个主程序已经可以正常启动，测试运行 2 小时期间，未发生异常。

测试程序： SunnyrainLovestory ，标示版本V1.0

再次向您的研究和工作致以谢意！
