### ISSUE TITLE
如何通过本项目已有文件进行解包？

### ISSUE THREAD

**Issue by Nagato-Kiangologiste** [YeLikesss/CNGALTools#4]
在技术方面基本上是白痴，之前靠着各位技术大佬们编好的Garbro, KRKRDump等程序进行游戏资源提取，刚刚看着教程摸明白了怎么通过VS生成可执行文件。
如今需要提取プトリカ 1st.cut的图片资源，想请教一下如何通过本项目已有文件完成游戏资源的提取，除了lightVN这个包以外，还需要些什么？

**Comment by YeLikesss** [comment]
1.VS打开LightVN解决方案
2.找到ConsoleExecute项目的Program.cs源码文件
3.找到Main函数, 修改代码中的游戏exe路径变量. 修改为你的游戏路径
4.编译运行

**Comment by Nagato-Kiangologiste** [comment]
已完成提取，感谢解答👌
